/**
 * Paper-style figure page: one or more illustrations, each with the mandatory
 * credit inside its figure legend, plus Acknowledgements and References.
 * Output is a self-contained HTML page (images embedded), ready to print to PDF.
 */
import type { Picture } from "./types.js";
import type { EmbeddedImage } from "./assets.js";
import { buildCitation, plain, bareDoi, type CitationOptions } from "./citation.js";

export interface FigureEntry {
  picture: Picture;
  image: EmbeddedImage;
}

export interface FigureDocOptions extends CitationOptions {
  /** Optional document title shown above the figures. */
  title?: string;
  /** Figure image width as a percentage of the column. Default 56. */
  imageWidthPct?: number;
}

const CSS = `
  @page { size: A4; margin: 22mm 20mm; }
  * { box-sizing: border-box; }
  html,body{ margin:0; padding:0; }
  body{ font-family:"Times New Roman","YuMincho","Hiragino Mincho ProN",serif;
        color:#111; line-height:1.7; font-size:10.5pt; }
  .paper{ max-width:170mm; margin:0 auto; }
  .demo-band{ text-align:center; font-size:7.5pt; letter-spacing:.12em; color:#888;
              text-transform:uppercase; margin:0 0 6pt; }
  h1.title{ font-size:14pt; text-align:center; margin:0 0 12pt; line-height:1.4; }
  hr.rule{ border:0; border-top:1px solid #000; margin:8pt 0 14pt; }
  .sec{ font-weight:bold; font-size:10.5pt; margin:12pt 0 4pt; }
  figure{ break-inside:avoid; margin:0 0 12pt; padding:8pt; border:.5pt solid #bbb; }
  figure img{ display:block; margin:0 auto 6pt; }
  figcaption{ font-size:8.7pt; line-height:1.55; text-align:justify; }
  figcaption .lab{ font-weight:bold; }
  .credit{ color:#222; } .credit a{ color:#000; }
  .refs{ font-size:8.7pt; } .refs p{ margin:0 0 4pt; padding-left:1.6em; text-indent:-1.6em; }
  .ack{ font-size:9pt; }
  .footer{ margin-top:14pt; border-top:.5pt solid #ccc; padding-top:5pt;
           font-size:7.6pt; color:#666; text-align:center; }
`;

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Numbered reference line (deduped upstream). */
function referenceLine(p: Picture, locale: "ja" | "en"): string {
  const c = buildCitation(p, { locale });
  const title = `${p.name_en || p.name}${p.name && p.name_en ? ` (${p.name})` : ""}`;
  const year = c.text.match(/©\s*(\d{4})/)?.[1] ?? "";
  return `DBCLS TogoTV. ${esc(title)}. Togo picture gallery${year ? `, ${year}` : ""}. ` +
    `CC-BY-4.0. ${c.doi}`;
}

export function buildFigureHtml(entries: FigureEntry[], opts: FigureDocOptions = {}): string {
  const locale = opts.locale ?? "en";
  const widthPct = opts.imageWidthPct ?? 56;
  const isJa = locale === "ja";

  const figures = entries
    .map((e, i) => {
      const p = e.picture;
      const c = buildCitation(p, opts);
      const title = isJa ? p.name : p.name_en || p.name;
      const both = isJa ? `${p.name}（${p.name_en}）` : `${p.name_en || p.name} (${p.name})`;
      const desc = plain(p.Description_small);
      const lab = isJa ? `図 ${i + 1}.` : `Fig. ${i + 1}.`;
      return `<figure>
      <img src="${e.image.dataUri}" alt="${esc(title)}" style="width:${widthPct}%">
      <figcaption><span class="lab">${lab}</span> ${esc(both)}${desc ? `。${esc(desc)}` : ""}
        <span class="credit">${c.html}</span></figcaption>
    </figure>`;
    })
    .join("\n");

  // Dedup by DOI for Acknowledgements / References.
  const seen = new Set<string>();
  const uniq = entries.filter((e) => {
    const k = bareDoi(e.picture.id);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  const ackHead = isJa ? "謝辞（Acknowledgements）" : "Acknowledgements";
  const ackBody = isJa
    ? "本資料中の図に用いたイラストについて —"
    : "The illustrations used in this material —";
  const ack = uniq.map((e) => buildCitation(e.picture, opts).html).join("<br>");

  const refsHead = isJa ? "引用文献（References）" : "References";
  const refs = uniq
    .map((e, i) => `<p>[${i + 1}] ${referenceLine(e.picture, locale)}</p>`)
    .join("\n");

  const titleHtml = opts.title ? `<h1 class="title">${esc(opts.title)}</h1><hr class="rule">` : "";
  const band = isJa
    ? "Figure layout — togopic-mcp が生成"
    : "Figure layout — generated by togopic-mcp";

  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><style>${CSS}</style></head>
<body><div class="paper">
  <div class="demo-band">${band}</div>
  ${titleHtml}
  ${figures}
  <div class="sec">${ackHead}</div>
  <p class="ack credit">${ackBody} ${ack}</p>
  <div class="sec">${refsHead}</div>
  <div class="refs">${refs}</div>
  <div class="footer">Illustrations © DBCLS TogoTV, licensed under CC-BY-4.0. Credit generated by togopic-mcp.</div>
</div></body></html>`;
}
